### ISSUE TITLE
Client only mod?

### ISSUE THREAD

**Issue by pavog** [CleverNucleus/ArmorRenderLib#1]
Hi, for me this seems like it is a client-only mod, right?
If so, why is the mod marked as "server side: optional" on [Modrinth](https://modrinth.com/mod/armor-render-lib)?

**Comment by CleverNucleus** [comment]
Hi there,
You are correct - this mod is client only. I think I must have originally marked server side support as optional because mods using the package can be used on the server. I'd argue now that server side support should be listed as unsupported; just forgot about it and haven't noticed since.
Thanks for the heads up!
